apiVersion: batch/v1
kind: Job
metadata:
  name: acquisitions-migration
  namespace: acquisitions
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: migrate
          image: acquisitions:prod
          imagePullPolicy: IfNotPresent
          command:
            - npx
            - drizzle-kit
            - migrate
          envFrom:
            - configMapRef:
                name: acquisitions-config
            - secretRef:
                name: acquisitions-secret
          env:
            - name: TMPDIR
              value: /tmp
          volumeMounts:
            - name: tmp
              mountPath: /tmp
