apiVersion: v1
kind: Secret
metadata:
  name: acquisitions-secret
  namespace: acquisitions
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://neondb_owner:npg_1vn9quOxYsZC@ep-rough-dawn-aine36b5-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
  ARCJET_KEY: 'ajkey_01kvs9hwv3ey99bmxdscz2b3f3'
  JWT_SECRET: 'asB4KNq14pK5gBl5aYWE67mQhhZzhzbO'
