apiVersion: v1
kind: Secret
metadata:
  name: acquisitions-secret
  namespace: acquisitions
type: Opaque
stringData:
  DATABASE_URL: 'postgres://neondb_owner:<password>@ep-xxx-pooler.<region>.aws.neon.tech/neondb?sslmode=require'
  ARCJET_KEY: 'your-arcjet-key'
  JWT_SECRET: 'your-jwt-secret-change-in-production'
