apiVersion: v1
kind: Secret
metadata:
  name: acquisitions-secret
  namespace: acquisitions
type: Opaque
stringData:
  DATABASE_URL: 'postgres://neon:npg@192.168.49.3:5432/neondb?sslmode=require'
  ARCJET_KEY: 'dev-arcjet-key'
  JWT_SECRET: 'dev-jwt-secret-minikube'
